### PR TITLE
New Crowdin updates

### PR DESCRIPTION
**Pull request by jbtronics**

### CODE REVIEW

**Comment by chr1st1an7** [comment]
Hi, 
I'm currently making the translation and I'd like to test out my current translation to see if every word fits right and to generally see what needs fixing, so I downloaded the .xlf files from Crowding and places them in the translations folder of my PartDB instance but it doesn't seem to load. Is there anything else I need to do?

**Comment by jbtronics** [comment]
You will probably need to clear the cache, so that Par-DB detects the changes

**Comment by chr1st1an7** [comment]
Thanks, now it works yes, and how could I enable dev mode? After I enable that the changes will automatically get applied?

**Comment by jbtronics** [comment]
You need to set APP_ENV in the .env.local to `dev` (maybe you need to do a composer install without the `--no-dev` option to work properly).

Then it should clear the cache automatically when you update the file.

**Pull request merged**
