### PR TITLE
Rewrite LCSC datasheet URL

### PR DESCRIPTION
**Pull request by vvekic**
Fixes https://github.com/Part-DB/Part-DB-server/issues/790 by rewriting datasheet.lcsc.com URL to www.lcsc.com/datasheet when fetching datasheet pdf.

### CODE REVIEW

**Comment by dm5tt** [comment]
This Patch still seems to cause issues:

image

**Comment by dm5tt** [comment]
This patch seems to cause problems - or LCSC.

image


How how to reproduce:
 1. Search a component like C5123440
 2. "500"-Popup comes

**Comment by vvekic** [comment]
> This patch seems to cause problems - or LCSC.
> 
> image
> 
> How how to reproduce:
> 
> 1. Search a component like C5123440
> 2. "500"-Popup comes

Will try to reproduce and fix if a bug was introduced.

**Comment by dm5tt** [comment]
Log from searching C5125440

```
"} {"token":{"authenticated":true,"roles":["ROLE_USER"],"user_identifier":"admin"},"url":"/en/tools/info_providers/search","ip":"192.168.1.197","http_method":"POST","server":"192.168.1.3","referrer":"http://192.168.1.3:8080/en/tools/info_providers/search"}
[2024-12-12T20:05:00.515685+00:00] cache.INFO: Lock acquired, now computing item "search_lcsc_C5123440" {"key":"search_lcsc_C5123440"} {"token":{"authenticated":true,"roles":["ROLE_USER"],"user_identifier":"admin"},"url":"/en/tools/info_providers/search","ip":"192.168.1.197","http_method":"POST","server":"192.168.1.3","referrer":"http://192.168.1.3:8080/en/tools/info_providers/search"}
[2024-12-12T20:05:00.515856+00:00] http_client.INFO: Request: "GET https://wmsc.lcsc.com/ftps/wm/search/global?keyword=C5123440" [] {"token":{"authenticated":true,"roles":["ROLE_USER"],"user_identifier":"admin"},"url":"/en/tools/info_providers/search","ip":"192.168.1.197","http_method":"POST","server":"192.168.1.3","referrer":"http://192.168.1.3:8080/en/tools/info_providers/search"}
[2024-12-12T20:05:01.284985+00:00] http_client.INFO: Response: "200 https://wmsc.lcsc.com/ftps/wm/search/global?keyword=C5123440" [] {"token":{"authenticated":true,"roles":["ROLE_USER"],"user_identifier":"admin"},"url":"/en/tools/info_providers/search","ip":"192.168.1.197","http_method":"POST","server":"192.168.1.3","referrer":"http://192.168.1.3:8080/en/tools/info_providers/search"}
[2024-12-12T20:05:01.285486+00:00] http_client.INFO: Request: "GET https://wmsc.lcsc.com/ftps/wm/product/detail?productCode=C5123440" [] {"token":{"authenticated":true,"roles":["ROLE_USER"],"user_identifier":"admin"},"url":"/en/tools/info_providers/search","ip":"192.168.1.197","http_method":"POST","server":"192.168.1.3","referrer":"http://192.168.1.3:8080/en/tools/info_providers/search"}
[2024-12-12T20:05:01.384933+00:00] http_client.INFO: Response: "200 https://wmsc.lcsc.com/ftps/wm/product/detail?productCode=C5123440" [] {"token":{"authenticated":true,"roles":["ROLE_USER"],"user_identifier":"admin"},"url":"/en/tools/info_providers/search","ip":"192.168.1.197","http_method":"POST","server":"192.168.1.3","referrer":"http://192.168.1.3:8080/en/tools/info_providers/search"}
[2024-12-12T20:05:01.385686+00:00] http_client.INFO: Request: "GET https://datasheet.lcsc.com/lcsc/2208041800_HEERMICR-HE61CN3302MR_C5123440.pdf" [] {"token":{"authenticated":true,"roles":["ROLE_USER"],"user_identifier":"admin"},"url":"/en/tools/info_providers/search","ip":"192.168.1.197","http_method":"POST","server":"192.168.1.3","referrer":"http://192.168.1.3:8080/en/tools/info_providers/search"}
[2024-12-12T20:05:01.565462+00:00] http_client.INFO: Response: "502 https://datasheet.lcsc.com/lcsc/2208041800_HEERMICR-HE61CN3302MR_C5123440.pdf" [] {"token":{"authenticated":true,"roles":["ROLE_USER"],"user_identifier":"admin"},"url":"/en/tools/info_providers/search","ip":"192.168.1.197","http_method":"POST","server":"192.168.1.3","referrer":"http://192.168.1.3:8080/en/tools/info_providers/search"}
[2024-12-12T20:05:01.566652+00:00] request.CRITICAL: Uncaught PHP Exception Symfony\Component\HttpClient\Exception\ServerException: "HTTP/2 502  returned for "https://datasheet.lcsc.com/lcsc/2208041800_HEERMICR-HE61CN3302MR_C5123440.pdf"." at CommonResponseTrait.php line 169 {"exception":"[object] (Symfony\\Component\\HttpClient\\Exception\\ServerException(code: 502): HTTP/2 502  returned for \"https://datasheet.lcsc.com/lcsc/2208041800_HEERMICR-HE61CN3302MR_C5123440.pdf\". at /var/www/html/vendor/symfony/http-client/Response/CommonResponseTrait.php:169)
[stacktrace]
#0 /var/www/html/vendor/symfony/http-client/Response/CommonResponseTrait.php(47): Symfony\\Component\\HttpClient\\Response\\CurlResponse->checkStatusCode()
#1 /var/www/html/vendor/symfony/http-client/Response/CurlResponse.php(229): Symfony\\Component\\HttpClient\\Response\\CurlResponse->doGetContent()
#2 /var/www/html/src/Services/InfoProviderSystem/Providers/LCSCProvider.php(105): Symfony\\Component\\HttpClient\\Response\\CurlResponse->getContent()
#3 /var/www/html/src/Services/InfoProviderSystem/Providers/LCSCProvider.php(298): App\\Services\\InfoProviderSystem\\Providers\\LCSCProvider->getRealDatasheetUrl()
#4 /var/www/html/src/Services/InfoProviderSystem/Providers/LCSCProvider.php(212): App\\Services\\InfoProviderSystem\\Providers\\LCSCProvider->getProductDatasheets()
#5 /var/www/html/src/Services/InfoProviderSystem/Providers/LCSCProvider.php(90): App\\Services\\InfoProviderSystem\\Providers\\LCSCProvider->getPartDetail()
#6 /var/www/html/src/Services/InfoProviderSystem/Providers/LCSCProvider.php(143): App\\Services\\InfoProviderSystem\\Providers\\LCSCProvider->queryDetail()
#7 /var/www/html/src/Services/InfoProviderSystem/Providers/LCSCProvider.php(336): App\\Services\\InfoProviderSystem\\Providers\\LCSCProvider->queryByTerm()
#8 /var/www/html/src/Services/InfoProviderSystem/PartInfoRetriever.php(82): App\\Services\\InfoProviderSystem\\Providers\\LCSCProvider->searchByKeyword()
#9 /var/www/html/vendor/symfony/cache/LockRegistry.php(111): App\\Services\\InfoProviderSystem\\PartInfoRetriever->App\\Services\\InfoProviderSystem\\{closure}()
#10 /var/www/html/vendor/symfony/cache/Traits/ContractsTrait.php(102): Symfony\\Component\\Cache\\LockRegistry::compute()
#11 /var/www/html/vendor/symfony/cache-contracts/CacheTrait.php(64): Symfony\\Component\\Cache\\Adapter\\AbstractAdapter->Symfony\\Component\\Cache\\Traits\\{closure}()
#12 /var/www/html/vendor/symfony/cache/Traits/ContractsTrait.php(85): Symfony\\Component\\Cache\\Adapter\\AbstractAdapter->contractsGet()
#13 /var/www/html/vendor/symfony/cache-contracts/CacheTrait.php(30): Symfony\\Component\\Cache\\Adapter\\AbstractAdapter->doGet()
#14 /var/www/html/src/Services/InfoProviderSystem/PartInfoRetriever.php(78): Symfony\\Component\\Cache\\Adapter\\AbstractAdapter->get()
#15 /var/www/html/src/Services/InfoProviderSystem/PartInfoRetriever.php(64): App\\Services\\InfoProviderSystem\\PartInfoRetriever->searchInProvider()
#16 /var/www/html/src/Controller/InfoProviderController.php(83): App\\Services\\InfoProviderSystem\\PartInfoRetriever->searchByKeyword()
#17 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(181): App\\Controller\\InfoProviderController->search()
#18 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(76): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw()
#19 /var/www/html/vendor/symfony/http-kernel/Kernel.php(197): Symfony\\Component\\HttpKernel\\HttpKernel->handle()
#20 /var/www/html/vendor/symfony/runtime/Runner/Symfony/HttpKernelRunner.php(35): Symfony\\Component\\HttpKernel\\Kernel->handle()
#21 /var/www/html/vendor/autoload_runtime.php(29): Symfony\\Component\\Runtime\\Runner\\Symfony\\HttpKernelRunner->run()
#22 /var/www/html/public/index.php(5): require_once('...')
#23 {main}
"} {"token":{"authenticated":true,"roles":["ROLE_USER"],"user_identifier":"admin"},"url":"/en/tools/info_providers/search","ip":"192.168.1.197","http_method":"POST","server":"192.168.1.3","referrer":"http://192.168.1.3:8080/en/tools/info_providers/search"}
[2024-12-12T20:05:01.571108+00:00] deprecation.INFO: User Deprecated: Since nelmio/security-bundle 3.4.0: The "Nelmio\SecurityBundle\EventListener\XssProtectionListener" class is deprecated, use Content Security Policy without allowing "unsafe-inline" scripts instead. {"exception":"[object] (ErrorException(code: 0): User Deprecated: Since nelmio/security-bundle 3.4.0: The \"Nelmio\\SecurityBundle\\EventListener\\XssProtectionListener\" class is deprecated, use Content Security Policy without allowing \"unsafe-inline\" scripts instead. at /var/www/html/vendor/nelmio/security-bundle/src/EventListener/XssProtectionListener.php:35)
[stacktrace]
#0 /var/www/html/vendor/nelmio/security-bundle/src/EventListener/XssProtectionListener.php(80): Nelmio\\SecurityBundle\\EventListener\\XssProtectionListener->__construct()
#1 /var/www/html/var/cache/docker/ContainerOveKFnc/App_KernelDockerContainer.php(2016): Nelmio\\SecurityBundle\\EventListener\\XssProtectionListener::fromConfig()
#2 /var/www/html/var/cache/docker/ContainerOveKFnc/App_KernelDockerContainer.php(475): ContainerOveKFnc\\App_KernelDockerContainer::getNelmioSecurity_XssProtectionListenerService()
#3 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(257): ContainerOveKFnc\\App_KernelDockerContainer::ContainerOveKFnc\\{closure}()
#4 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(220): Symfony\\Component\\EventDispatcher\\EventDispatcher::Symfony\\Component\\EventDispatcher\\{closure}()
#5 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(56): Symfony\\Component\\EventDispatcher\\EventDispatcher->callListeners()
#6 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(214): Symfony\\Component\\EventDispatcher\\EventDispatcher->dispatch()
#7 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(202): Symfony\\Component\\HttpKernel\\HttpKernel->filterResponse()
#8 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(76): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw()
#9 /var/www/html/vendor/symfony/http-kernel/EventListener/ErrorListener.php(117): Symfony\\Component\\HttpKernel\\HttpKernel->handle()
#10 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(260): Symfony\\Component\\HttpKernel\\EventListener\\ErrorListener->onKernelException()
#11 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(220): Symfony\\Component\\EventDispatcher\\EventDispatcher::Symfony\\Component\\EventDispatcher\\{closure}()
#12 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(56): Symfony\\Component\\EventDispatcher\\EventDispatcher->callListeners()
#13 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(239): Symfony\\Component\\EventDispatcher\\EventDispatcher->dispatch()
#14 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(91): Symfony\\Component\\HttpKernel\\HttpKernel->handleThrowable()
#15 /var/www/html/vendor/symfony/http-kernel/Kernel.php(197): Symfony\\Component\\HttpKernel\\HttpKernel->handle()
#16 /var/www/html/vendor/symfony/runtime/Runner/Symfony/HttpKernelRunner.php(35): Symfony\\Component\\HttpKernel\\Kernel->handle()
#17 /var/www/html/vendor/autoload_runtime.php(29): Symfony\\Component\\Runtime\\Runner\\Symfony\\HttpKernelRunner->run()
#18 /var/www/html/public/index.php(5): require_once()
#19 {main}
"} {"token":{"authenticated":true,"roles":["ROLE_USER"],"user_identifier":"admin"},"url":"/en/tools/info_providers/search","ip":"192.168.1.197","http_method":"POST","server":"192.168.1.3","referrer":"http://192.168.1.3:8080/en/tools/info_providers/search"}
[2024-12-12T20:05:01.571980+00:00] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} {"token":{"authenticated":true,"roles":["ROLE_USER"],"user_identifier":"admin"},"url":"/en/tools/info_providers/search","ip":"192.168.1.197","http_method":"POST","server":"192.168.1.3","referrer":"http://192.168.1.3:8080/en/tools/info_providers/search"}
192.168.1.197 - - [12/Dec/2024:20:05:00 +0000] "POST /en/tools/info_providers/search HTTP/1.1" 500 4279 "http://192.168.1.3:8080/en/tools/info_providers/search" "Mozilla/5.0 (X11; Linux x86_64; rv:133.0) Gecko/20100101 Firefox/133.0"
- -  12/Dec/2024:20:05:00 +0000 "POST /index.php" 500
```

Verified the patch in the file and cleaned cache.

**Comment by dm5tt** [comment]
OK - found the issue.


```
 if ($url !== null && trim($url) !== '' && preg_match("/^https:\/\/(datasheet\.lcsc\.com|www\.lcsc\.com\/datasheet)\/.*(C\d+)\.pdf$/", $url, $matches) > 0) {`
```

The first part of the preg_match regular regular expression causes it to fall back to the old URL.

Following change makes it work:

```
if ($url !== null && trim($url) !== '' && preg_match("/^www\.lcsc\.com\/datasheet\/.*(C\d+)\.pdf$/", $url, $matches) > 0) {
```

**Comment by dm5tt** [comment]
Your patch fixes the issue. Sorry for the noise.

There was a really weird caching that stuck on executing the old code.

**Pull request merged**
